# Server settings
server:
    tomcat:
        basedir: /var/tmp/oneblog/blog-web
# SPRING PROFILES
spring:
    profiles:
        include: [center]

# logging settings
logging:
    config: classpath:logback-spring.xml
    file:
      path: /var/tmp/oneblog/logs
    level:
      root: INFO
      com.zyd: INFO

# braum过滤器，用于过滤恶意请求
braum:
  limit:
      access:
          type: redis
          threshold: 50
          interval: 5000

####################################自定义配置##########################################
app:
    # 测试环境关闭验证码
    enableKaptcha: ${ONEBLOG_APP_ENABLE_KAPTCHA:false}
    # 测试环境不打印配置信息
    enabledPrintConfig: ${ONEBLOG_APP_ENABLE_PRINT_CONFIG:false}
    # 测试环境关闭 redis 缓存
    enableRedisCache: ${ONEBLOG_ENABLE_REDIS_CACHE:false}
####################################自定义配置##########################################
